version: 0.2

phases:
  build:
    commands:
      - echo "Fetching Current Lambda Version..."
      - export CurrentVersion=$(aws lambda get-alias --function-name MaToolAPI --name dev --query 'FunctionVersion' --output text)
      - echo "CurrentVersion: $CurrentVersion"

  post_build:
    commands:
      - echo "Publishing New Lambda Version..."
      - export TargetVersion=$(aws lambda publish-version --function-name MaToolAPI --query 'Version' --output text)
      - echo "TargetVersion: $TargetVersion"

      - echo "Replacing placeholders in appspec.yml..."
      - sed -i "s/{{CurrentVersion}}/$CurrentVersion/g" appspec.yml
      - sed -i "s/{{TargetVersion}}/$TargetVersion/g" appspec.yml

      - echo "Final appspec.yml contents:"
      - cat appspec.yml

artifacts:
  files:
    - "**/*"
