version: 0.2
phases:
  install:
    commands: #AWS CLIをインストール
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - ./aws/install --install-dir /usr/local/aws-cli --update
      - npm install
  pre_build:
    commands:
      - echo No Pre Build phase
  build: #更新前のバージョンを取得した上で、関数の更新を実行
    commands:
      - echo Build started on `date`
      - CurrentVersion=$(echo $(aws lambda get-alias --function-name MaToolAPI --name prod | grep FunctionVersion | tail -1 |tr -cd 0-9))
      - zip -r lambda.zip ./index.js
      - aws lambda update-function-code --function-name MaToolAPI --zip-file fileb://lambda.zip
      - sleep 10
  post_build: #新バージョンを発行し、エイリアスに紐づいているバージョンを新バージョンに変更
    commands:
      - echo Build completed on `date`
      - ls
      - aws lambda publish-version --function-name MaToolAPI --description "update version"
      - TargetVersion=$(echo $(aws lambda list-versions-by-function --function-name MaToolAPI | grep Version | tail -1 | tr -cd 0-9))
      - echo $CurrentVersion
      - echo $TargetVersion
      - aws lambda update-alias --function-name MaToolAPI --name prod --function-version $TargetVersion
      - aws lambda delete-function --function-name MaToolAPI --qualifier $CurrentVersion
