version: 0.2
phases:
  install:
    commands: #AWS CLIをインストール
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - ./aws/install --install-dir ~/aws-cli --bin-dir ~/bin --update
      - export PATH=~/bin:$PATH
      - npm install
  pre_build:
    commands:
      - echo No Pre Build phase
  build: #更新前のバージョンを取得した上で、関数の更新を実行
    commands:
      - echo Build started on `date`
      - CurrentVersion=$(aws lambda get-alias --function-name MaToolAPI --name dev --query 'FunctionVersion' --output text)
      - zip -r lambda.zip ./*
      - aws lambda update-function-code --function-name MaToolAPI --zip-file fileb://lambda.zip
      - sleep 10
  post_build: #新バージョンを発行し、エイリアスに紐づいているバージョンを新バージョンに変更
    commands:
      - echo Build completed on `date`
      - ls
      - aws lambda publish-version --function-name MaToolAPI --description "update version"
      - TargetVersion=$(aws lambda list-versions-by-function --function-name MaToolAPI --query 'Versions[-1].Version' --output text)
      - echo $CurrentVersion
      - echo $TargetVersion
      - LC_ALL=C.UTF-8 aws lambda update-alias --function-name MaToolAPI --name dev --function-version $TargetVersion
      # - aws lambda delete-function --function-name MaToolAPI --qualifier $CurrentVersion
      - |
        if [ "$CurrentVersion" != "$TargetVersion" ]; then
          aws lambda delete-function --function-name MaToolAPI --qualifier $CurrentVersion
        fi
